### ISSUE TITLE
Unknown result code: 4

### ISSUE THREAD

**Issue by fpauser** [MatthiasLohr/docker-f5fpc#20]
As requested:

```bash
Please enter your VPN password: 
Waiting...
Unknown result code: 4
Please create an issue with this code here:
https://github.com/MatthiasLohr/docker-f5fpc/issues/new

Additional information:
Connection Status: retrieving favorites list
Favorites Information:
______________________
fav-Id   fav-Type  fav-Status       fav-Name
Connection established successfully
```

**Comment by MatthiasLohr** [comment]
Interesting... no idea what that means. Did you try it again? Did that happen only once or can you reproduce it?

**Comment by fpauser** [comment]
Happened only once...

Am Mo., 4. März 2019 um 12:25 Uhr schrieb Matthias Lohr <
notifications@github.com>:

**Comment by cruscio** [comment]
Fwiw, I see this result code almost every time I connect from my home network, but almost nowhere else: coffee shops, company offices, other residential wifi networks, etc.

**Comment by MatthiasLohr** [comment]
Mh. Any idea about the meaning of that?

It seems to be some kind of intermediary result if the connection is not completely established yet...

**Comment by max-len** [comment]
As it says, it is "retrieving favorites list". Happens almost every time for me, but doesn't have an impact on the by then already working connection.
