### ISSUE TITLE
Force split tunnel

### ISSUE THREAD

**Issue by drobwolf** [MatthiasLohr/docker-f5fpc#23]
When connecting via the CLI on f5fpc is there a way to force split tunneling?

**Comment by drobwolf** [comment]
To clarify: I see that the gateway mode  allows one to PREVENT a split tunnel, but I’m wondering if there is a way to FORCE a split tunnel in f5fpc?

**Comment by drobwolf** [comment]
To clarify: I see that the gateway mode  allows one to PREVENT a split tunnel, but I’m wondering if there is a way to FORCE a split tunnel in f5fpc?

**Comment by drobwolf** [comment]
To clarify: I see that the gateway mode  allows one to PREVENT a split tunnel, but I’m wondering if there is a way to FORCE a split tunnel in f5fpc?

**Comment by drobwolf** [comment]
To clarify: I see that the gateway mode  allows one to PREVENT a split tunnel, but I’m wondering if there is a way to FORCE a split tunnel in f5fpc?

**Comment by drobwolf** [comment]
To clarify: I see that the gateway mode  allows one to PREVENT a split tunnel, but I’m wondering if there is a way to FORCE a split tunnel in f5fpc?

**Comment by drobwolf** [comment]
To clarify: I see that the gateway mode  allows one to PREVENT a split tunnel, but I’m wondering if there is a way to FORCE a split tunnel in f5fpc?

**Comment by drobwolf** [comment]
To clarify: I see that the gateway mode  allows one to PREVENT a split tunnel, but I’m wondering if there is a way to FORCE a split tunnel in f5fpc?

**Comment by MatthiasLohr** [comment]
Actually, this is what this repository is for. f5fpc will always do a full tunnel (respectively, it will do what is defined by the server, which is usually a full tunnel).

Using this project, the full tunnel is created within a docker container and you can decide which subnets should be routed to the container, using it as a router, and which subnet should use other routers. Very easy way to have split tunneling.
